### PR TITLE
Fix Exception when SET CONSTRAINT Where condition excludes all objects

### LINKED ISSUE #56: "unknown class" - Exception wenn ALL im SET CONSTRAINT leer ist
Wenn das Resultat der WHERE-Filterung im SET CONSTRAINT leer ist, dann retourniert beispielsweise die Funktion PolylinesOverlap() einen unknown class Fehler.

Das folgende Beispiel basiert auf den Unit-Test-Daten der Funktion PolylinesOverlap (Testdata.xtf // enthält keine Objekte mit type == #4) :

```
    CLASS TestClass =
      geometry : POLYLINE WITH (STRAIGHTS) VERTEX CHKoord WITHOUT OVERLAPS > 0.001;
      type : (t1,t2,t3,t4);

      SET CONSTRAINT setConstraintT2or3 : WHERE type == #t4 : GeoW_FunctionsExt.PolylinesOverlap(ALL, "geometry");

    END TestClass;
```

Beobachteter Fehler:

> Info: .\TestData.xtf: TestSuite.FunctionTestTopic BID=TestSuite.FunctionTestTopic
> Info:       8 objects in CLASS TestSuite.FunctionTestTopic.TestClass
> Error: unknown class in TestSuite.FunctionTestTopic.TestClass.setConstraintT2or3
> Info: ...validation failed

Alle Funktionen müssen dahingehend geprüft werden, dass sie bei leerer Inputmenge keine Evaluierung versuchen

### PR DESCRIPTION
**Pull request by patrickackermann**
resolves https://github.com/GeoWerkstatt/geow-interlis-functions/issues/56

### CODE REVIEW

File: src/test/java/ch/geowerkstatt/ilivalidator/extensions/functions/PolylinesOverlapIoxPluginTest.java [hunk 1]
```diff
@@ -32,12 +41,24 @@ void polylinesOverlap() throws Ili2cFailure, IoxException {
...
+    @Test
+    void setConstraintEverythingFilteredOut() throws Ili2cFailure, IoxException {
+        vh.runValidation(new String[]{TEST_DATA_ONLY_T2}, new String[]{"PolylinesOverlap/PolylinesOverlap.ili"});
+        assertEquals(3, vh.getErrs().size());
+        AssertionHelper.assertConstraintErrors(vh, 1, "setConstraintAllNoOverlaps");
+        AssertionHelper.assertConstraintErrors(vh, 1, "setConstraintT1");
+        AssertionHelper.assertNoConstraintError(vh, "setConstraintT2");
+        AssertionHelper.assertConstraintErrors(vh, 1, "setConstraintT3");
+        AssertionHelper.assertNoConstraintError(vh, "setConstraintT1or2"); // One line in T1 is a segment of T2
+        AssertionHelper.assertNoConstraintError(vh, "setConstraintT2or3"); // The lines in T2 and T3 are equal
```
Comment (domi-b) [inline src/test/java/ch/geowerkstatt/ilivalidator/extensions/functions/PolylinesOverlapIoxPluginTest.java]: PP: Diese Kommentare passen nicht zu den Daten im neuen XTF.

**Review by domi-b — APPROVED** [review]
